# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region  = "us-east-1"
  profile = "my-aws-profile"

  default_tags {
    tags = {
      environment = "prod"
      region      = "us-east-1"
      managedBy   = "terraform"
    }
  }
}
