# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "terragrunt-my-org-my-aws-profile"
    encrypt = true
    key     = "us-east-1/my-account/zesty/account/terraform.tfstate"
    profile = "my-aws-profile"
    region  = "us-east-1"
  }
}
